version: '3.6'

services:
  react:
    build: 
      context: .
      dockerfile: react/dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./react:/usr/react/
    restart: 'always'

  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/flask