version: '3.7'

services:
  front:
    build: 
      context: ./front
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    stdin_open: true
    tty: true
    restart: 'always'

  flask:
    build:
      context: .
      dockerfile: dockerfile 
    volumes:
      - .:/app
    command: python main.py
    ports:
      - "5000:5000"
    depends_on:
      - front
