version: '3.7'

services:
  reactapp:
    build: 
      context: ./react
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
    restart: 'always'

  flask:
    build:
      context: ./flask
      dockerfile: dockerfile 
    volumes:
      - .:/app
    command: python main.py
    ports:
      - "5000:5000"
    depends_on:
      - reactapp
