version: '3.7'

services:
  reactapp:
    build: 
      context: .
      dockerfile: react/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react:/usr/app
    stdin_open: true
    tty: true
    restart: 'always'

  flask:
    build:
      context: .
      dockerfile: dockerfile 
    volumes:
      - .:/app
    command: python main.py
    ports:
      - "5000:5000"
    depends_on:
      - reactapp
