version: '3.7'

services:
  reactapp:
    build: 
      context: ./react-app
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./react-app:/app
    restart: 'always'

  flask:
    build:
      context: ./flask
      dockerfile: dockerfile 
    volumes:
      - .:/app
    command: python main.py
    ports:
      - "5000:5000"
    depends_on:
      - react-app
